[package]
name = "hangman"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
rand = "0.8"
colorgrad = "0.7.0"
crossterm = "0.29.0"
tui-gradient-block = "0.1.3"
tui-rule = "0.1.2"
